EXEC recurso_create 'Proyector multimedia'
EXEC recurso_create 'Pizarra blanca'
EXEC recurso_create 'Computadora portátil'
EXEC recurso_create 'Mesa de trabajo'
EXEC recurso_create 'Silla ergonómica'
EXEC recurso_create 'Tablero de dibujo'
EXEC recurso_create 'Herramientas eléctricas'
EXEC recurso_create 'Equipo de soldadura'
EXEC recurso_create 'Cámara de video'
EXEC recurso_create 'Micrófono inalámbrico'
EXEC recurso_create 'Herramientas de carpintería'
EXEC recurso_create 'Kit de electrónica'
EXEC recurso_create 'Máquina de coser'
EXEC recurso_create 'Equipo de grabación de audio'
EXEC recurso_create 'Horno de cerámica'
EXEC recurso_create 'Mesa de corte'
EXEC recurso_create 'Telar de tejido'
EXEC recurso_create 'Máquina de serigrafía'
EXEC recurso_create 'Herramientas de jardinería'
