EXEC aplicacion_x_equipo_create 1, 1
EXEC aplicacion_x_equipo_create 1, 2
EXEC aplicacion_x_equipo_create 2, 3
EXEC aplicacion_x_equipo_create 2, 4
EXEC aplicacion_x_equipo_create 3, 5
EXEC aplicacion_x_equipo_create 3, 6
EXEC aplicacion_x_equipo_create 4, 7
EXEC aplicacion_x_equipo_create 4, 8
EXEC aplicacion_x_equipo_create 5, 9
EXEC aplicacion_x_equipo_create 5, 10
EXEC aplicacion_x_equipo_create 6, 11
EXEC aplicacion_x_equipo_create 6, 12
EXEC aplicacion_x_equipo_create 7, 13
EXEC aplicacion_x_equipo_create 7, 14
EXEC aplicacion_x_equipo_create 8, 15
EXEC aplicacion_x_equipo_create 8, 16
EXEC aplicacion_x_equipo_create 9, 17
EXEC aplicacion_x_equipo_create 9, 18
EXEC aplicacion_x_equipo_create 10, 19
EXEC aplicacion_x_equipo_create 10, 20
