-- Ejecutar el procedimiento almacenado para crear nuevos distribuidores oficiales
EXEC distribuidor_oficial_create 'Soluciones Tecnológicas Avanzadas S.A.'
EXEC distribuidor_oficial_create 'Innovación en Tecnología y Software'
EXEC distribuidor_oficial_create 'Líderes en Desarrollo Tecnológico'
EXEC distribuidor_oficial_create 'Expertos en Soluciones Digitales'
EXEC distribuidor_oficial_create 'Servicios Tecnológicos Globales'
EXEC distribuidor_oficial_create 'Plataforma Digital Integral'
EXEC distribuidor_oficial_create 'Especialistas en Tecnología y Software'
EXEC distribuidor_oficial_create 'Soluciones Informáticas Innovadoras'
EXEC distribuidor_oficial_create 'Tecnología de Vanguardia Ltda.'
EXEC distribuidor_oficial_create 'Soluciones Avanzadas en Hardware'
EXEC distribuidor_oficial_create 'Innovación Tecnológica y Servicios'
EXEC distribuidor_oficial_create 'Desarrollo Tecnológico Estratégico'
EXEC distribuidor_oficial_create 'Alianza Tecnológica Innovadora'
EXEC distribuidor_oficial_create 'Servicios Informáticos Avanzados'
EXEC distribuidor_oficial_create 'Tecnología Moderna y Soluciones'
EXEC distribuidor_oficial_create 'Especialistas en Soluciones Tecnológicas'
EXEC distribuidor_oficial_create 'Soluciones Integrales en Software'
EXEC distribuidor_oficial_create 'Innovación en Tecnología Digital'
EXEC distribuidor_oficial_create 'Desarrollo Tecnológico Global'
EXEC distribuidor_oficial_create 'Tecnología de Punta y Servicios'
