EXEC taller_create 120, 'Introducción a la Programación'
EXEC taller_create 90, 'Diseño de Interfaces de Usuario'
EXEC taller_create 150, 'Programación Avanzada con Python'
EXEC taller_create 180, 'Desarrollo Web con HTML, CSS y JavaScript'
EXEC taller_create 120, 'Introducción al Desarrollo de Videojuegos'
EXEC taller_create 90, 'Fundamentos de la Inteligencia Artificial'
EXEC taller_create 150, 'Análisis de Datos con R'
EXEC taller_create 180, 'Creación de Aplicaciones Móviles'
EXEC taller_create 120, 'Diseño Gráfico Digital'
EXEC taller_create 90, 'Inglés para Programadores'
EXEC taller_create 150, 'Seguridad Informática'
EXEC taller_create 180, 'Desarrollo de Aplicaciones Empresariales'
EXEC taller_create 120, 'Diseño de Experiencia de Usuario (UX)'
EXEC taller_create 90, 'Desarrollo de Habilidades de Comunicación'
EXEC taller_create 150, 'Gestión de Proyectos de Software'
EXEC taller_create 180, 'Introducción a la Realidad Virtual y Aumentada'
EXEC taller_create 120, 'Marketing Digital'
EXEC taller_create 90, 'Introducción a la Robótica'
EXEC taller_create 150, 'Optimización de Bases de Datos'
EXEC taller_create 180, 'Desarrollo Ágil de Software'
