EXEC escuela_x_taller_docente_create 10, 1, 3, '2024-03-01' -- Escuela "San Antonio", taller "Matemáticas Avanzadas", docente "María Gutiérrez"
EXEC escuela_x_taller_docente_create 3, 4, 5, '2024-03-02' -- Escuela "San Pablo", taller "Biología Molecular", docente "Juan Martínez"
EXEC escuela_x_taller_docente_create 6, 5, 4, '2024-03-03' -- Escuela "Santa Lucía", taller "Programación Web", docente "Ana Pérez"
EXEC escuela_x_taller_docente_create 7, 7, 8, '2024-03-04' -- Escuela "San Andrés", taller "Historia del Arte", docente "Luis Rodríguez"
EXEC escuela_x_taller_docente_create 9, 8, 7, '2024-03-05' -- Escuela "Santa Isabel", taller "Química Orgánica", docente "Elena Sánchez"
EXEC escuela_x_taller_docente_create 12, 9, 6, '2024-03-06' -- Escuela "San Francisco", taller "Física Cuántica", docente "Carlos Fernández"
EXEC escuela_x_taller_docente_create 15, 10, 5, '2024-03-07' -- Escuela "San Lorenzo", taller "Literatura Contemporánea", docente "Laura González"
EXEC escuela_x_taller_docente_create 17, 11, 4, '2024-03-08' -- Escuela "Santa Marta", taller "Arqueología", docente "Javier Martínez"
EXEC escuela_x_taller_docente_create 19, 12, 3, '2024-03-09' -- Escuela "San Ignacio", taller "Introducción a la Economía", docente "Marta Díaz"
EXEC escuela_x_taller_docente_create 20, 13, 2, '2024-03-10' -- Escuela "Santa Cecilia", taller "Diseño Gráfico", docente "Pedro López"
EXEC escuela_x_taller_docente_create 3, 14, 1, '2024-03-11' -- Escuela "San Marcos", taller "Robótica", docente "Julia Rodríguez"
EXEC escuela_x_taller_docente_create 5, 15, 9, '2024-03-12' -- Escuela "Santa Teresa", taller "Arquitectura", docente "Hugo Martínez"
EXEC escuela_x_taller_docente_create 6, 16, 8, '2024-03-13' -- Escuela "San Juan", taller "Historia del Arte", docente "Ana Gómez"
EXEC escuela_x_taller_docente_create 8, 17, 7, '2024-03-14' -- Escuela "Santa Clara", taller "Programación Web", docente "Sergio González"
EXEC escuela_x_taller_docente_create 1, 18, 6, '2024-03-15' -- Escuela "San Nicolás", taller "Literatura Contemporánea", docente "Eva Martínez"
EXEC escuela_x_taller_docente_create 2, 19, 5, '2024-03-16' -- Escuela "Santa Catalina", taller "Arqueología", docente "Andrés López"
EXEC escuela_x_taller_docente_create 4, 20, 4, '2024-03-17' -- Escuela "San Salvador", taller "Introducción a la Economía", docente "Laura Díaz"
EXEC escuela_x_taller_docente_create 6, 1, 3, '2024-03-18' -- Escuela "Santa Bárbara", taller "Diseño Gráfico", docente "Gabriel Pérez"
EXEC escuela_x_taller_docente_create 8, 2, 2, '2024-03-19' -- Escuela "San Lucas", taller "Robótica", docente "Carmen Martínez"
EXEC escuela_x_taller_docente_create 4, 3, 1, '2024-03-20' -- Escuela "Santa Elena", taller "Historia del Arte", docente "José Rodríguez"
