EXEC materia_create 'Introducción a la Programación'
EXEC materia_create 'Algoritmos y Estructuras de Datos'
EXEC materia_create 'Programación Orientada a Objetos'
EXEC materia_create 'Desarrollo Web'
EXEC materia_create 'Bases de Datos'
EXEC materia_create 'Ingeniería de Software'
EXEC materia_create 'Redes de Computadoras'
EXEC materia_create 'Sistemas Operativos'
EXEC materia_create 'Inteligencia Artificial'
EXEC materia_create 'Seguridad Informática'
EXEC materia_create 'Análisis y Diseño de Sistemas'
EXEC materia_create 'Desarrollo de Aplicaciones Móviles'
EXEC materia_create 'Computación en la Nube'
EXEC materia_create 'Ingeniería de Requisitos'
EXEC materia_create 'Interacción Humano-Computadora'
EXEC materia_create 'Minería de Datos'
EXEC materia_create 'Ciberseguridad'
EXEC materia_create 'Programación Avanzada'
EXEC materia_create 'Sistemas Distribuidos'
EXEC materia_create 'Realidad Virtual y Aumentada'
