EXEC taller_x_recurso_create 1, 1
EXEC taller_x_recurso_create 2, 1
EXEC taller_x_recurso_create 3, 2
EXEC taller_x_recurso_create 4, 2
EXEC taller_x_recurso_create 5, 3
EXEC taller_x_recurso_create 6, 3
EXEC taller_x_recurso_create 7, 4
EXEC taller_x_recurso_create 8, 4
EXEC taller_x_recurso_create 9, 5
EXEC taller_x_recurso_create 10, 5
EXEC taller_x_recurso_create 11, 6
EXEC taller_x_recurso_create 12, 6
EXEC taller_x_recurso_create 13, 7
EXEC taller_x_recurso_create 14, 7
EXEC taller_x_recurso_create 15, 8
EXEC taller_x_recurso_create 17, 9
EXEC taller_x_recurso_create 18, 9
EXEC taller_x_recurso_create 19, 10
EXEC taller_x_recurso_create 3, 10