EXEC oficina_create 'Oficina de Tecnología Educativa';
EXEC oficina_create 'Centro de Innovación Tecnológica';
EXEC oficina_create 'Oficina de Investigación y Desarrollo';
EXEC oficina_create 'Laboratorio de Informática';
EXEC oficina_create 'Centro de Recursos Digitales';
EXEC oficina_create 'Oficina de Aprendizaje en Línea';
EXEC oficina_create 'Centro de Tecnología Educativa';
EXEC oficina_create 'Oficina de Servicios Informáticos';
EXEC oficina_create 'Centro de Excelencia en Tecnología';
EXEC oficina_create 'Oficina de Apoyo Tecnológico';
EXEC oficina_create 'Centro de Recursos Multimedia';
EXEC oficina_create 'Oficina de Tecnología y Aprendizaje';
EXEC oficina_create 'Centro de Información y Tecnología';
EXEC oficina_create 'Oficina de Educación Virtual';
EXEC oficina_create 'Centro de Tecnología Avanzada';
EXEC oficina_create 'Oficina de Desarrollo Académico';
EXEC oficina_create 'Centro de Recursos Tecnológicos';
EXEC oficina_create 'Oficina de Servicios Digitales';
EXEC oficina_create 'Centro de Innovación Pedagógica';
EXEC oficina_create 'Oficina de Tecnología e Innovación';
