EXEC disco_rigido_create 'Seagate', 500
EXEC disco_rigido_create 'Western Digital', 1000
EXEC disco_rigido_create 'Samsung', 2000
EXEC disco_rigido_create 'Toshiba', 500
EXEC disco_rigido_create 'Kingston', 250
EXEC disco_rigido_create 'Crucial', 500
EXEC disco_rigido_create 'SanDisk', 1000
EXEC disco_rigido_create 'Intel', 250
EXEC disco_rigido_create 'Corsair', 500
EXEC disco_rigido_create 'HP', 1000
EXEC disco_rigido_create 'Dell', 2000
EXEC disco_rigido_create 'Adata', 250
EXEC disco_rigido_create 'Hitachi', 500
EXEC disco_rigido_create 'Transcend', 1000
EXEC disco_rigido_create 'Sony', 2000
EXEC disco_rigido_create 'Crucial', 500
EXEC disco_rigido_create 'Lexar', 250
EXEC disco_rigido_create 'Maxtor', 500
EXEC disco_rigido_create 'Patriot', 1000
EXEC disco_rigido_create 'PNY', 2000
