EXEC orientacion_create 'Orientación en Ciencias Sociales y Humanidades'
EXEC orientacion_create 'Orientación en Economía y Administración'
EXEC orientacion_create 'Orientación en Ciencias Naturales y Salud'
EXEC orientacion_create 'Orientación en Arte y Diseño'
EXEC orientacion_create 'Orientación en Tecnología e Informática'
EXEC orientacion_create 'Orientación en Comunicación y Medios'
EXEC orientacion_create 'Orientación en Educación Física y Deportes'
EXEC orientacion_create 'Orientación en Idiomas y Literatura'
EXEC orientacion_create 'Orientación en Matemáticas y Física'
EXEC orientacion_create 'Orientación en Química y Biología'
EXEC orientacion_create 'Orientación en Ciencias Agrarias y Ambientales'
EXEC orientacion_create 'Orientación en Turismo y Hotelería'
EXEC orientacion_create 'Orientación en Construcción y Arquitectura'
EXEC orientacion_create 'Orientación en Derecho y Ciencias Sociales'
EXEC orientacion_create 'Orientación en Informática y Programación'
EXEC orientacion_create 'Orientación en Ciencias Políticas y Relaciones Internacionales'
EXEC orientacion_create 'Orientación en Psicología y Ciencias del Comportamiento'
EXEC orientacion_create 'Orientación en Ingeniería y Tecnología Industrial'
EXEC orientacion_create 'Orientación en Arte y Cultura'
EXEC orientacion_create 'Orientación en Ciencias de la Computación'
