EXEC escuela_x_orientacion_create 1, 1
EXEC escuela_x_orientacion_create 1, 2
EXEC escuela_x_orientacion_create 2, 3
EXEC escuela_x_orientacion_create 2, 4
EXEC escuela_x_orientacion_create 3, 5
EXEC escuela_x_orientacion_create 3, 6
EXEC escuela_x_orientacion_create 4, 7
EXEC escuela_x_orientacion_create 4, 8
EXEC escuela_x_orientacion_create 5, 9
EXEC escuela_x_orientacion_create 5, 10
EXEC escuela_x_orientacion_create 6, 11
EXEC escuela_x_orientacion_create 6, 12
EXEC escuela_x_orientacion_create 7, 13
EXEC escuela_x_orientacion_create 7, 14
EXEC escuela_x_orientacion_create 8, 15
EXEC escuela_x_orientacion_create 8, 16
EXEC escuela_x_orientacion_create 9, 17
EXEC escuela_x_orientacion_create 9, 18
EXEC escuela_x_orientacion_create 10, 19
EXEC escuela_x_orientacion_create 10, 20
