EXEC docente_x_materia_x_escuela_create 3, 12, 8
EXEC docente_x_materia_x_escuela_create 5, 4, 11
EXEC docente_x_materia_x_escuela_create 2, 15, 18
EXEC docente_x_materia_x_escuela_create 1, 20, 7
EXEC docente_x_materia_x_escuela_create 4, 8, 16
EXEC docente_x_materia_x_escuela_create 17, 6, 14
EXEC docente_x_materia_x_escuela_create 13, 19, 3
EXEC docente_x_materia_x_escuela_create 11, 2, 9
EXEC docente_x_materia_x_escuela_create 9, 11, 10
EXEC docente_x_materia_x_escuela_create 7, 18, 13
EXEC docente_x_materia_x_escuela_create 20, 1, 2
EXEC docente_x_materia_x_escuela_create 16, 5, 17
EXEC docente_x_materia_x_escuela_create 19, 16, 12
EXEC docente_x_materia_x_escuela_create 14, 10, 1
EXEC docente_x_materia_x_escuela_create 6, 9, 20
EXEC docente_x_materia_x_escuela_create 8, 14, 19
EXEC docente_x_materia_x_escuela_create 12, 17, 15
EXEC docente_x_materia_x_escuela_create 10, 7, 6
EXEC docente_x_materia_x_escuela_create 15, 3, 4
